service: medical-departures
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  timeout: 15
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /


